# Generated by Django 5.1.3 on 2024-11-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('industry_aggregation_nzsioc', models.CharField(max_length=255)),
                ('industry_code_nzsioc', models.CharField(max_length=50)),
                ('industry_name_nzsioc', models.CharField(max_length=255)),
                ('units', models.CharField(max_length=50)),
                ('variable_code', models.CharField(max_length=50)),
                ('variable_name', models.CharField(max_length=255)),
                ('variable_category', models.CharField(max_length=255)),
                ('value', models.FloatField()),
                ('industry_code_anzsic06', models.TextField()),
            ],
        ),
    ]
