# Generated by Django 5.1.3 on 2024-11-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_processing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industrydata',
            name='value',
            field=models.IntegerField(),
        ),
    ]
