# Generated by Django 5.1.3 on 2024-11-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_processing', '0002_alter_industrydata_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industrydata',
            name='value',
            field=models.FloatField(),
        ),
    ]
