# Generated by Django 5.1.3 on 2024-11-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_processing', '0003_alter_industrydata_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('progress', models.FloatField(default=0.0)),
                ('status', models.CharField(default='Started', max_length=255)),
            ],
        ),
    ]
