nginx:
  container_name: nginx
  image: nginx:latest
  ports:
    - "80:80"
  volumes:
    - ./nginx/nginx.local.conf:/etc/nginx/conf.d/default.conf
    - static-volume:/app/var/static
  depends_on:
    - django-server
django-server:
  build: .
  environment:
    - TZ=Asia/Almaty
  depends_on:
    - postgresql
    - redis
  volumes:
    - static-volume:/app/var/static
  deploy:
    replicas: 3
