version: "3.8"
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.local.conf:/etc/nginx/conf.d/default.conf
      - static-volume:/app/var/static
    depends_on:
      - django-server
  django-server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=Asia/Almaty
    volumes:
      - static-volume:/app/var/static
    deploy:
      replicas: 2

volumes:
  static-volume: