# Generated by Django 5.1.3 on 2024-11-24 07:07

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=encrypted_model_fields.fields.EncryptedCharField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=encrypted_model_fields.fields.EncryptedCharField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=encrypted_model_fields.fields.EncryptedEmailField(),
        ),
    ]
